In [2]:
import pandas as pd

file_path = 'C:\\Users\\colem\\Downloads\\Spring 2022 Outcome Report.csv'

data = pd.read_csv(file_path)
dataframe = pd.DataFrame(data)

dataframe

,student name,student id,student sis id,assessment title,assessment id,assessment type,submission date,submission score,learning outcome name,learning outcome id,...,assignment url,learning outcome friendly name,learning outcome points possible,learning outcome mastery score,learning outcome mastered,learning outcome rating,learning outcome rating points,account id,account name,enrollment state
0,NaN,13328,NaN,My Theology Paper: Comparing and Contrasting ...,422281,assignment,2022-04-18T13:29:48-06:00,200.0,GE_CF2_U1415 Christian Formation 2,400,...,https://nnu.instructure.com/courses/28474/assi...,Christian Formation 2,3.0,2.0,1.0,Exemplary: Articulate distinctive characterist...,3.0,107,Undergraduate Philosophy and Religion,active
1,NaN,17704,NaN,My Theology Paper: Comparing and Contrasting ...,422281,assignment,2022-05-01T21:26:54-06:00,160.0,GE_CF2_U1415 Christian Formation 2,400,...,https://nnu.instructure.com/courses/28474/assi...,Christian Formation 2,3.0,2.0,0.0,Minimum: List the characteristics of Wesleyan ...,1.0,107,Undergraduate Philosophy and Religion,active
2,NaN,20155,NaN,My Theology Paper: Comparing and Contrasting ...,422281,assignment,2022-05-02T22:17:02-06:00,190.0,GE_CF2_U1415 Christian Formation 2,400,...,https://nnu.instructure.com/courses/28474/assi...,Christian Formation 2,3.0,2.0,1.0,Exemplary: Articulate distinctive characterist...,3.0,107,Undergraduate Philosophy and Religion,active
3,NaN,21601,NaN,My Theology Paper: Comparing and Contrasting ...,422281,assignment,2022-05-02T22:36:29-06:00,180.0,GE_CF2_U1415 Christian Formation 2,400,...,https://nnu.instructure.com/courses/28474/assi...,Christian Formation 2,3.0,2.0,1.0,Target: Compare and contrast Wesleyan theology...,2.0,107,Undergraduate Philosophy and Religion,active
4,NaN,24034,NaN,My Theology Paper: Comparing and Contrasting ...,422281,assignment,2022-05-02T20:32:54-06:00,190.0,GE_CF2_U1415 Christian Formation 2,400,...,https://nnu.instructure.com/courses/28474/assi...,Christian Formation 2,3.0,2.0,1.0,Exemplary: Articulate distinctive characterist...,3.0,107,Undergraduate Philosophy and Religion,active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,NaN,40928,NaN,Argument Essay Final Draft,466450,assignment,2022-05-02T00:12:44-06:00,198.0,GE_IP4_U2021,3647,...,https://nnu.instructure.com/courses/28700/assi...,Intellectual and Practical Skills 4,NaN,NaN,1.0,Exemplary: Research multiple sources of infor...,NaN,87,Undergraduate Langauge & Lit,active
1495,NaN,41052,NaN,Argument Essay Final Draft,464908,assignment,2022-05-03T23:26:37-06:00,140.0,GE_IP4_U2021,3647,...,https://nnu.instructure.com/courses/29652/assi...,Intellectual and Practical Skills 4,NaN,NaN,0.0,Outcome Not Met,NaN,87,Undergraduate Langauge & Lit,active
1496,NaN,41073,NaN,Argument Essay Final Draft,466450,assignment,2022-04-29T23:58:24-06:00,160.0,GE_IP4_U2021,3647,...,https://nnu.instructure.com/courses/28700/assi...,Intellectual and Practical Skills 4,NaN,NaN,1.0,Target: Research information in response to c...,NaN,87,Undergraduate Langauge & Lit,active
1497,NaN,41102,NaN,Argument Essay Final Draft,466450,assignment,2022-04-29T21:40:59-06:00,175.0,GE_IP4_U2021,3647,...,https://nnu.instructure.com/courses/28700/assi...,Intellectual and Practical Skills 4,NaN,NaN,1.0,Target: Research information in response to c...,NaN,87,Undergraduate Langauge & Lit,active
1498,NaN,41120,NaN,Final Paper Due,467000,assignment,2022-04-29T23:52:11-06:00,125.0,GE_IP4_U2021,3647,...,https://nnu.instructure.com/courses/28779/assi...,Intellectual and Practical Skills 4,3.0,2.0,0.0,"Minimum: Locate, access, and utilize informati...",1.0,85,Undergraduate Humanities,active

In [4]:
columns = []
for column in dataframe:
    columns.append(column)

for column in columns:
    print(column)

student name
student id
student sis id
assessment title
assessment id
assessment type
submission date
submission score
learning outcome name
learning outcome id
attempt
outcome score
assessment question
assessment question id
course name
course id
course sis id
section name
section id
section sis id
assignment url
learning outcome friendly name
learning outcome points possible
learning outcome mastery score
learning outcome mastered
learning outcome rating
learning outcome rating points
account id
account name
enrollment state

In [5]:
print(dataframe[['student id', 'learning outcome name', 'learning outcome friendly name', 'course sis id', 'assessment title', 'learning outcome rating', 'learning outcome rating points']])

      student id               learning outcome name  \
0          13328  GE_CF2_U1415 Christian Formation 2
1          17704  GE_CF2_U1415 Christian Formation 2
2          20155  GE_CF2_U1415 Christian Formation 2
3          21601  GE_CF2_U1415 Christian Formation 2
4          24034  GE_CF2_U1415 Christian Formation 2
...          ...                                 ...
1494       40928                        GE_IP4_U2021
1495       41052                        GE_IP4_U2021
1496       41073                        GE_IP4_U2021
1497       41102                        GE_IP4_U2021
1498       41120                        GE_IP4_U2021

           learning outcome friendly name        course sis id  \
0                   Christian Formation 2   SP2022_THEO2100_03
1                   Christian Formation 2   SP2022_THEO2100_03
2                   Christian Formation 2   SP2022_THEO2100_03
3                   Christian Formation 2   SP2022_THEO2100_03
4                   Christian Formation 2   SP2022_THEO2100_03
...                                   ...                  ...
1494  Intellectual and Practical Skills 4  SP2022_ENGL1030B_02
1495  Intellectual and Practical Skills 4  SP2022_ENGL1030B_01
1496  Intellectual and Practical Skills 4  SP2022_ENGL1030B_02
1497  Intellectual and Practical Skills 4  SP2022_ENGL1030B_02
1498  Intellectual and Practical Skills 4   SP2022_HNRS2560_01

                                       assessment title  \
0     My Theology Paper:  Comparing and Contrasting ...
1     My Theology Paper:  Comparing and Contrasting ...
2     My Theology Paper:  Comparing and Contrasting ...
3     My Theology Paper:  Comparing and Contrasting ...
4     My Theology Paper:  Comparing and Contrasting ...
...                                                 ...
1494                         Argument Essay Final Draft
1495                         Argument Essay Final Draft
1496                         Argument Essay Final Draft
1497                         Argument Essay Final Draft
1498                                    Final Paper Due

                                learning outcome rating  \
0     Exemplary: Articulate distinctive characterist...
1     Minimum: List the characteristics of Wesleyan ...
2     Exemplary: Articulate distinctive characterist...
3     Target: Compare and contrast Wesleyan theology...
4     Exemplary: Articulate distinctive characterist...
...                                                 ...
1494  Exemplary:  Research multiple sources of infor...
1495                                    Outcome Not Met
1496  Target:  Research information in response to c...
1497  Target:  Research information in response to c...
1498  Minimum: Locate, access, and utilize informati...

      learning outcome rating points
0                                3.0
1                                1.0
2                                3.0
3                                2.0
4                                3.0
...                              ...
1494                             NaN
1495                             NaN
1496                             NaN
1497                             NaN
1498                             1.0

[1499 rows x 7 columns]

In [14]:
for index, row in dataframe.iterrows():
    if(index < len(columns)):
        print(str(index) + ": " + columns[index] + "\t" + str(row[index]))

0: student name	nan
1: student id	17704
2: student sis id	nan
3: assessment title	My Theology Paper:  Comparing and Contrasting Wesleyan Theology with My Own Christian Theological Tradition
4: assessment id	422281
5: assessment type	assignment
6: submission date	2022-04-30T16:47:32-06:00
7: submission score	180.0
8: learning outcome name	GE_CF2_U1415 Christian Formation 2
9: learning outcome id	400
10: attempt	1
11: outcome score	1.0
12: assessment question	nan
13: assessment question id	nan
14: course name	INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03
15: course id	28474
16: course sis id	SP2022_THEO2100_03
17: section name	INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03
18: section id	26153
19: section sis id	nan
20: assignment url	https://nnu.instructure.com/courses/28474/assignments/422281
21: learning outcome friendly name	Christian Formation 2
22: learning outcome points possible	3.0
23: learning outcome mastery score	2.0
24: learning outcome mastered	1.0
25: learning outcome rating	Minimum: List the characteristics of Wesleyan theology.
26: learning outcome rating points	2.0
27: account id	107
28: account name	Undergraduate Philosophy and Religion
29: enrollment state	active

In [67]:
## Specify what indexes we care about
indexes_of_interest = [1,6,8,14,16,17,25,26]
columns_of_interest = []
for val in indexes_of_interest:
    for cIndex, col in enumerate(columns):
        if (cIndex == val):
            columns_of_interest.append(columns[val])

student_ids = []            #index=1
submission_dates = []       #index=6
learning_outcome_codes = []  #index=7
learning_outcome_years = []
course_names =[]            #index=14
course_sis_ids = []         #index=16
section_names = []          #index=17
learning_outcome_rating = []#index=25
learning_outcome_points = []#index=26


## Read data from the dataframe
## For some columns, the information will be manipulated
for index, rows in dataframe.iterrows():
    student_ids.append(rows[1])

    ## Manipulate the date, so that we only get YYYY-MM-DD
    submission_dates.append(str(rows[6]).split('T')[0])

    ## Manipulate the learning outcome name, seperating into code and year
    learning_outcome_name = rows[8].split('_')
    if(len(learning_outcome_name) > 2):
        learning_outcome_years.append(learning_outcome_name[2])
        learning_outcome_codes.append(learning_outcome_name[1])
    elif(len(learning_outcome_name) > 1):
        learning_outcome_codes.append(learning_outcome_name[1])
        learning_outcome_years.append('NaN')
    else:
        learning_outcome_codes.append(learning_outcome_name[0])
        learning_outcome_years.append('NaN')


    ## Leave as is for now
    course_names.append(rows[14])
    course_sis_ids.append(rows[16])
    section_names.append(rows[17])

    # Manipulate the rating, getting rid of everything except for the actual value
    learning_outcome_rating.append(str(rows[25]).split(':')[0])
    
    # Leave points as is, maybe convert to int
    learning_outcome_points.append(rows[26])

columns_of_interest

['student id',
 'submission date',
 'learning outcome name',
 'course name',
 'course sis id',
 'section name',
 'learning outcome rating',
 'learning outcome rating points']

In [68]:
new_data = pd.DataFrame(list(zip(submission_dates, learning_outcome_codes, learning_outcome_years, course_names, course_sis_ids, section_names, learning_outcome_rating, learning_outcome_points))
,index = student_ids)

new_data

,0,1,2,3,4,5,6,7
13328,2022-04-18,CF2,U1415 Christian Formation 2,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,SP2022_THEO2100_03,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,Exemplary,3.0
17704,2022-05-01,CF2,U1415 Christian Formation 2,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,SP2022_THEO2100_03,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,Minimum,1.0
20155,2022-05-02,CF2,U1415 Christian Formation 2,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,SP2022_THEO2100_03,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,Exemplary,3.0
21601,2022-05-02,CF2,U1415 Christian Formation 2,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,SP2022_THEO2100_03,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,Target,2.0
24034,2022-05-02,CF2,U1415 Christian Formation 2,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,SP2022_THEO2100_03,INTRO CHRISTIAN THEOLOGY SP2022_THEO2100_03,Exemplary,3.0
...,...,...,...,...,...,...,...,...
40928,2022-05-02,IP4,U2021,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_02,SP2022_ENGL1030B_02,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_02,Exemplary,NaN
41052,2022-05-03,IP4,U2021,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_01,SP2022_ENGL1030B_01,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_01,Outcome Not Met,NaN
41073,2022-04-29,IP4,U2021,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_02,SP2022_ENGL1030B_02,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_02,Target,NaN
41102,2022-04-29,IP4,U2021,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_02,SP2022_ENGL1030B_02,UNIVERSITY WRITING/RESEARCH B SP2022_ENGL1030B_02,Target,NaN
41120,2022-04-29,IP4,U2021,WSTRN INTELLECTUAL TRAD II SP2022_HNRS2560_01,SP2022_HNRS2560_01,WSTRN INTELLECTUAL TRAD II SP2022_HNRS2560_01,Minimum,1.0